version: '3.1'

services:
  db:
    image: postgres
    restart: always
    networks:
    - ethindexer
    env_file: .env
    ports:
      - "5437:5432"
    volumes:
    - indexer:/var/lib/postgresql/data
    labels:
      traefik.enable: "false"

volumes:
  indexer:

networks:
  ethindexer:
