---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-server
  namespace: ethindexer-indexer
  labels:
    app: indexer
    component: server
    ethindexerapi: enabled
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
      component: server
  template:
    metadata:
      labels:
        app: indexer
        component: server
        ethindexerapi: enabled
    spec:
      containers:
      - name: server
        image: registry.lestak.sh/ethindexer-indexer:41
        args: ["server"]
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        envFrom:
          - secretRef:
              name: indexer
        ports:
          - containerPort: 8081
            name: http
        livenessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          tcpSocket:
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 3
 
---
apiVersion: v1
kind: Service
metadata:
  name: indexer-server
  namespace: ethindexer-indexer
  labels:
    app: indexer
    component: server
spec:
  type: ClusterIP
  selector:
    app: indexer
    component: server
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      name: http-app