---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-redis
  namespace: ethindexer-indexer
spec:
  maxReplicaCount: 100
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: indexer-worker
  triggers:
  - type: redis
    metadata:
      address: redis.ethindexer-indexer.svc.cluster.local:6379
      listName: polygon:blocks
      listLength: "10"
  - type: redis
    metadata:
      address: redis.ethindexer-indexer.svc.cluster.local:6379
      listName: ethereum:blocks
      listLength: "10"
